#!/usr/bin/env python

import roslib
roslib.load_manifest('depth_driver')
import rospy
from std_msgs.msg import Header

from depth_driver.msg import Float64Stamped

rospy.init_node('fake_depth')

pub = rospy.Publisher('/depth', Float64Stamped)

while True:
    pub.publish(Float64Stamped(
        header=Header(
            stamp=rospy.Time.now(),
            frame_id='/map',
        ),
        data=0,
    ))
    rospy.sleep(rospy.Duration(.2))
