#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('auvsi_robosub')
import rospy

import auvsi_robosub.missions
import uf_smach.util
from uf_smach import missions
import smach_ros

def main():
    rospy.init_node('mission_planner')

    missionserver = missions.MissionServer(['main', 'hydrophone'])
    missionserver.get_plan('main').extend([
            missions.PlanEntry('starting_gate', 120, None, None),
            missions.PlanEntry('buoy', 120, 'hydrophone', 'any'),
            missions.PlanEntry('hedge', 120, 'hydrophone', 'any'),
            missions.PlanEntry('bins', 120, 'hydrophone', 'right'),
            missions.PlanEntry('shooter_approach', 120, 'hydrophone', None),
            missions.PlanEntry('shooter', 120, 'hydrophone', None),
            missions.PlanEntry('bins_return', 120, 'hydrophone', None),
            missions.PlanEntry('manipulation', 120, 'hydrophone', 'left'),
            missions.PlanEntry('hydrophone_grab', 120, None, None),
            missions.PlanEntry('grabber', 120, None, None),
            missions.PlanEntry('surface', 120, None, None),
            missions.PlanEntry('hydrophone_drop', 120, None, None),
            missions.PlanEntry('grabber_drop', 120, None, None)])
    missionserver.get_plan('hydrophone').extend([
            missions.PlanEntry('hydrophone_grab', 120, None, None),
            missions.PlanEntry('grabber', 120, None, None),
            missions.PlanEntry('surface', 120, None, None),
            missions.PlanEntry('hydrophone_drop', 120, None, None),
            missions.PlanEntry('grabber_drop', 120, None, None)])
            
    rospy.spin()
    
if __name__ == '__main__':
    main()
