#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('auvsi_robosub')
import rospy

import auvsi_robosub.missions
import uf_smach.util
from uf_smach import missions
import smach_ros

def main():
    rospy.init_node('mission_planner')

    missionserver = missions.MissionServer(['main', 'timeout'], master_timeout=12*60)
    missionserver.get_plan('main').extend([
            missions.PlanEntry('starting_gate', 120, None, None, 0),
            missions.PlanEntry('buoy', 120, 'timeout', 'any', 0),
            missions.PlanEntry('hedge', 120, 'timeout', 'any', 0),
            missions.PlanEntry('bins', 180, 'timeout', 'right', 2),
            missions.PlanEntry('shooter_approach', 120, 'timeout', None, 0),
            missions.PlanEntry('shooter', 120, 'timeout', None, 0),
            missions.PlanEntry('bins_return', 120, 'timeout', None, 0),
            missions.PlanEntry('manipulation', 180, 'timeout', 'left', 8)])
    missionserver.get_plan('timeout').extend([
            missions.PlanEntry('hydrophone_grab', 120, None, None, 0),
            missions.PlanEntry('grabber', 120, None, None, 0),
            missions.PlanEntry('surface', 120, None, None, 0),
            missions.PlanEntry('hydrophone_drop', 120, None, None, 0),
            missions.PlanEntry('grabber_drop', 120, None, None, 0)])
            
    rospy.spin()
    
if __name__ == '__main__':
    main()
