#!/usr/bin/env python

import sys
import roslib; roslib.load_manifest('auvsi_robosub')
import rospy

import auvsi_robosub.missions
import auvsi_robosub.missionconfigs
import uf_smach.util
from uf_smach import missions

def main():
    rospy.init_node('run_missions')

    shared = uf_smach.util.StateSharedHandles()
    
    names = sys.argv[1:]
    plan = missions.make_plan_state_machine(shared, names)

    missions.run_plans({'main': plan})

if __name__ == '__main__':
    main()
