#!/usr/bin/env python

"does a barrel roll"

import random

import roslib
roslib.load_manifest('sub_launch')
import rospy
import actionlib

from uf_common.orientation_helpers import PoseEditor
from uf_common.msg import MoveToAction

rospy.init_node('barrel_roll')

client = actionlib.SimpleActionClient('moveto', MoveToAction)
client.wait_for_server()
go = client.send_goal_and_wait

print 'Waiting for current position...'
p = PoseEditor.from_Odometry_topic()

go(p)

print 'Sending goal...'
client.send_goal(p.as_MoveToGoal(
    angular=[1000 if random.randrange(2) else -1000, 0, 0]))

print 'Waiting until rolled 90 degrees to send final pose...'
while True:
    p_now = PoseEditor.from_PoseTwistStamped_topic('/trajectory')
    if p_now.body_up_vector.dot(p.body_up_vector) < 0:
        break

print 'Sending final pose...'
go(p)
