#!/usr/bin/env python

from __future__ import division

import roslib
roslib.load_manifest('sub_launch')
import rospy

from kill_handling.broadcaster import KillBroadcaster


rospy.init_node('kill')

kill_br = KillBroadcaster(id=rospy.get_name(), lifetime=rospy.Duration(5), description='Command-line kill')

while not rospy.is_shutdown():
    kill_br.send(True)
    rospy.sleep(rospy.Duration(.1))
