#!/usr/bin/env python

import os
import random
import yaml

import roslib
roslib.load_manifest('sub_launch')
import rospy

rospy.init_node('param_saver', anonymous=True)

period = rospy.get_param('~period', 3)
filename = rospy.get_param('~filename')
file_basepath = rospy.get_param('~file_basepath')
param_paths = rospy.get_param('~param_paths')

while not rospy.is_shutdown():
    rospy.sleep(period)
    p = rospy.get_param(file_basepath)
    data = yaml.dump(dict((k, v) for k, v in p.iteritems() if k in param_paths))
    
    if os.path.exists(filename):
        with open(filename, 'rb') as f:
            if f.read() == data:
                continue
    
    tmp_filename = '%s.%i' % (filename, random.randrange(10000))
    with open(tmp_filename, 'wb') as f:
        f.write(data)
    os.rename(tmp_filename, filename)
