#!/usr/bin/env python

import yaml

import roslib
roslib.load_manifest('sub_launch')
import rospy

rospy.init_node('param_saver', anonymous=True)

period = rospy.get_param('~period', 3)
filename = rospy.get_param('~filename')
file_basepath = rospy.get_param('~file_basepath')
param_paths = rospy.get_param('~param_paths')

while not rospy.is_shutdown():
    rospy.sleep(period)
    p = rospy.get_param(file_basepath)
    p = dict((k, v) for k, v in p.iteritems() if k in param_paths)
    open(filename, 'wb').write(yaml.dump(p))
