#!/usr/bin/env python

import argparse
import math

import numpy

import roslib; roslib.load_manifest('sub_launch')
import rospy
import actionlib
from std_msgs.msg import Header
from geometry_msgs.msg import Pose, Quaternion, Point
from nav_msgs.msg import Odometry
from tf import transformations

from uf_common import orientation_helpers
from uf_common.msg import MoveToAction, MoveToGoal, PoseTwist
from uf_common.orientation_helpers import xyz_array, xyzw_array
from object_finder.msg import FindAction, FindGoal


rospy.init_node('bump_buoy')


visionclient = actionlib.SimpleActionClient('find', FindAction)
print 'Waiting for server...'
visionclient.wait_for_server()


client = actionlib.SimpleActionClient('moveto', MoveToAction)
print 'Waiting for server...'
client.wait_for_server()
print 'ok'

current = orientation_helpers.PoseEditor.from_Odometry_topic()
client.send_goal(current)

went = False
ignore = False

def got_feedback(fb):
    global current, went, ignore
    obj_pose = orientation_helpers.PoseEditor.from_Pose(goal.header.frame_id, fb.pose)
    if ignore: return
    print fb
    if fb.P_within_10cm > .2 or went:
        # approach mode
        
        current = current.set_position(obj_pose.position + obj_pose.forward_vector*2)
        #current = current.look_at(obj_pose.position)
        client.send_goal(current)
        went = True
    else:
        # search mode
        current = current.look_at(obj_pose.position)
        client.send_goal(current)

guess_pos = current.position + current.forward_vector * 5

goal = FindGoal()
goal.header.frame_id = current.header.frame_id
goal.type = goal.TYPE_OBJECT
goal.object_filename = roslib.packages.resource_file('auvsi_robosub', 'models', 'path.obj')
goal.prior_distribution.pose.position = Point(*guess_pos)
goal.prior_distribution.pose.orientation.w = 1
goal.prior_distribution.covariance[0+6*0] = 1
goal.prior_distribution.covariance[1+6*1] = 1
goal.prior_distribution.covariance[2+6*2] = 1
goal.prior_distribution.covariance[5+6*5] = 100
visionclient.send_goal(goal, feedback_cb=got_feedback)

rospy.spin()
