#!/usr/bin/env python

import argparse

import roslib; roslib.load_manifest('sub_launch')
import rospy
import actionlib
from std_msgs.msg import Header
from geometry_msgs.msg import Pose, Quaternion, Point

from c3_trajectory_generator.msg import MoveToAction, MoveToGoal

parser = argparse.ArgumentParser()
parser.add_argument('x', metavar='X', type=float)
parser.add_argument('y', metavar='Y', type=float)
parser.add_argument('z', metavar='Z', type=float)
args = parser.parse_args()

rospy.init_node('send_waypoint')
client = actionlib.SimpleActionClient('moveto', MoveToAction)
print 'Waiting for server...'
client.wait_for_server()

print 'Sending goal...'
print client.send_goal(MoveToGoal(
    header=Header(
        frame_id='/map',
    ),
    pose=Pose(
        position=Point(
            x=args.x,
            y=args.y,
            z=args.z,
        ),
        orientation=Quaternion(0, 0, 0, 1),
    ),
))
print 'Press enter to cancel...'
raw_input()
client.cancel_goal()
print 'Done.'
